name: flutter_one_signal
description: Flutter OneSignal
version: 0.1.0
author: Ihor Klimov <ihor@myhexaville.com>
homepage: https://github.com/IhorKlimov/Flutter-One-Signal

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.myhexaville.flutteronesignal
    pluginClass: FlutterOneSignalPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"